"""Add category_order to categories

Revision ID: c366226711e7
Revises: 
Create Date: 2024-07-31 00:34:24.048374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c366226711e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_categories_category_order'), 'categories', ['category_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_category_order'), table_name='categories')
    op.drop_column('categories', 'category_order')
    # ### end Alembic commands ###
